# Generated by Django 4.0.4 on 2022-05-27 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0002_registro_tiempo_total_registro_total_pagar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='total_pagar',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Total a pagar'),
        ),
    ]
