# Generated by Django 4.0.4 on 2022-05-27 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0003_alter_registro_total_pagar'),
    ]

    operations = [
        migrations.AddField(
            model_name='registro',
            name='pago_status',
            field=models.BooleanField(default=False),
        ),
    ]
