# Generated by Django 4.0.4 on 2022-05-27 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0004_registro_pago_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='registro',
            name='vehiculo_status',
            field=models.BooleanField(default=False),
        ),
    ]
