# Generated by Django 4.0.4 on 2022-05-27 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0005_registro_vehiculo_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registro',
            name='vehiculo_status',
        ),
    ]
