# Generated by Django 4.0.4 on 2022-05-27 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0006_remove_registro_vehiculo_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registro',
            old_name='Vehiculo',
            new_name='vehiculo',
        ),
    ]
