# Generated by Django 4.0.4 on 2022-05-27 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0002_vehiculo_vehiculo_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='vehiculo_status',
            field=models.BooleanField(default=False),
        ),
    ]
